FROM java

LABEL maintainer "misha"

COPY /project/springboot-helloworld/target/springboot-helloworld-0.0.1-SNAPSHOT.jar /usr/src/myapp/springboot-helloworld-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar springboot-helloworld-0.0.1-SNAPSHOT.jar